create table if not exists revenue (id integer generated by default as identity, locationid integer not null, salesdate date, salessum decimal(19,2) not null);
alter table revenue add constraint FK_revenue_location foreign key (locationid) references location;
alter table revenue add constraint FK_locationid_salesdate unique (locationid, salesdate);